[project]
name = "pgserver" # Required
version = "0.0.1"  # Required
description = "Postgres server with pgvector extension" # Required
readme = "README.md" # Optional
requires-python = ">=3.8"
license = {file = "LICENSE.txt"}
urls={repository="https://github.com/orm011/postgresql-wheel"}
authors=[{ name="Oscar Moll", email="orm@csail.mit.edu" }]
keywords=["postgresql", "pgvector"]
dependencies = [
    "fasteners>=0.19",
    "platformdirs>=4.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
include = ["postgresql*"]  # package names should match these glob patterns (["*"] by default)

[tool.pytest.ini_options]
testpaths = ["src/postgresql/tests"]

[tool.cibuildwheel]
before-all = "make"
test-requires = "pytest"
test-command = "pytest --pyargs postgresql"


[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"