name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        
    - name: Build
      run: |
        sudo apt install -y libreadline-dev zlib1g-dev
        bash src/tools/install_pg.sh refs/tags/13.4.1
        sudo python setup.py install
        python -m pytest postgresql.tests
