name: Build Wheels
on:
  release:
    types:
      - created
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # using macos-latest-xlarge for arm64 apple build:
          # macos-latest can cross compile for arm64, even though it is a x86_64 system
          # (see pyav build workflow)
          # however the build code for pg extensions themselves can depend on some generated binaries
          # (like pg_config), which would have been cross-compiled and cannot run on the host
          # to keep things simple just build on the -xlarge instance, which is arm64.exclude:
          # ubuntu arm64 may have similar issues (but useful for newer aws machines)
          # - os: macos-latest-xlarge
          #   arch: arm64
          # - os: macos-latest
          #   arch: x86_64
          - os: ubuntu-20.04 # for testing
            arch: x86_64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        if: matrix.os != 'ubuntu-20.04'
        with:
          python-version: '3.10'
      - uses: actions/setup-python@v4
        if: matrix.os == 'ubuntu-20.04'
          # for testing due to docker env issues
        with:
          python-version: '3.8'
      - name: Install cibuildwheel
        run: | 
          python -m pip install --upgrade pip
          python -m pip install --upgrade cibuildwheel
      - name: Build wheels
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_SKIP: pp* *-musllinux*
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
          name: python-package-distributions
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist
      - name: Install and test ubuntu wheel
        if: matrix.os == 'ubuntu-20.04'
        # test ubuntu outside of cibuildwheel due to postgres root user issues
        run: |
          python -m pip install --upgrade pip pytest
          python -m pip install --force-reinstall dist/*cp38*manylinux*x86*.whl
          pytest ./tests
  publish-to-pypi:
    name: Publish Python dist to PyPI
    needs:
    - build_wheels
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pgserver  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
        - name: Download all the dists
          uses: actions/download-artifact@v3
          with:
            name: python-package-distributions
            path: dist/
        - name: Publish distribution 📦 to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
