name: Build Wheels

on:
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
            arch: x86_64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install cibuildwheel
        run: | 
          python -m pip install --upgrade pip
          python -m pip install --upgrade cibuildwheel
      - name: Build wheels
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_SKIP: pp*  *-musllinux*
          CIBW_BEFORE_ALL: '(cd src/postgres/pgbuild && make)'
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: artifact
      #     path: dist
      # - uses: pypa/gh-action-pypi-publish@v1.4.2
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_TOKEN }}
